//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.03.24 at 08:44:23 PM MSK
//


package org.bambrikii.photobank.web.dtutils.remoteuploader3.handlers.model.persistencecontainer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.bambrikii.ru.psfotos.dtutils.remoteuploader3.handlers.model.persistencecontainer package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bambrikii.ru.psfotos.dtutils.remoteuploader3.handlers.model.persistencecontainer
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersistenceContainer }
     *
     */
    public PersistenceContainer createPersistenceContainer() {
        return new PersistenceContainer();
    }

    /**
     * Create an instance of {@link FailedFiles }
     *
     */
    public FailedFiles createFailedFiles() {
        return new FailedFiles();
    }

    /**
     * Create an instance of {@link UploadItem }
     *
     */
    public UploadItem createUploadItem() {
        return new UploadItem();
    }

}
