ALTER TABLE `site_users` MODIFY COLUMN `date_of_birth` DATETIME DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `site_users` MODIFY COLUMN `address` VARCHAR(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
